# Docker compose configuration file for building a
# mesos environment

version: '2'

services:
  weavescope:
    image: weaveworks/scope:latest
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
      - "app.weave.addr"
      - "0.0.0.0"

  zookeeper:
    image: jplock/zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"

  marathon:
    image: mesosphere/marathon:latest
    hostname: marathon
    ports:
      - "8080:8080"
    links:
      - zookeeper
    environment:
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/schedulers/marathon
      - MARATHON_HOSTNAME=marathon
      - MARATHON_HTTP_PORT=8080

  mesos-master:
    image: mesosphere/mesos-master:1.1.01.1.0-2.0.107.ubuntu1404
    hostname: mesos-master
    privileged: true
    command: /mesos/build/bin/mesos-master.sh
    ports:
      - "5050:5050"
    links:
      - zookeeper
    environment:
      - MESOS_IP=0.0.0.0
      - MESOS_HOSTNAME=0.0.0.0
      - MESOS_PORT=5050
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_LOG_DIR=/var/log
      - MESOS_ZK=zk://zookeeper:2181/mesos

  mesos-slave-1:
    image: mesosphere/mesos-slave:1.1.01.1.0-2.0.107.ubuntu1404
    privileged: true
    command: "\rm -rf /var/lib/mesos/meta/slaves/latest && /mesos/build/bin/mesos-slave.sh"
    ports:
      - "2201:2201"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    links:
      - zookeeper
    environment:
      - MESOS_IP=0.0.0.0
      - MESOS_PORT=2201
      - MESOS_HOSTNAME=0.0.0.0
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log
      - MESOS_WORK_DIR=/var/lib/mesos

  mesos-slave-2:
    image: mesosphere/mesos-slave:1.1.01.1.0-2.0.107.ubuntu1404
    privileged: true
    command: "\rm -rf /var/lib/mesos/meta/slaves/latest && /mesos/build/bin/mesos-slave.sh"
    ports:
      - "2202:2202"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    links:
      - zookeeper
    environment:
      - MESOS_IP=0.0.0.0
      - MESOS_PORT=2202
      - MESOS_HOSTNAME=0.0.0.0
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log
      - MESOS_WORK_DIR=/var/lib/mesos

  mesos-slave-3:
    image: mesosphere/mesos-slave:1.1.01.1.0-2.0.107.ubuntu1404
    privileged: true
    command: "\rm -rf /var/lib/mesos/meta/slaves/latest && /mesos/build/bin/mesos-slave.sh"
    ports:
      - "2203:2203"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    links:
      - zookeeper
    environment:
      - MESOS_IP=0.0.0.0
      - MESOS_PORT=2203
      - MESOS_HOSTNAME=0.0.0.0
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log
      - MESOS_WORK_DIR=/var/lib/mesos
