# Docker compose configuration file for building a
# mesos environment

version: '2'

services:
  weavescope:
    image: weaveworks/scope:latest
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
      - "app.weave.addr"
      - "0.0.0.0"

  zookeeper:
    image: jplock/zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"

  mesos-master:
    image: mesosphere/mesos-master:1.1.01.1.0-2.0.107.ubuntu1404
    hostname: mesos-master
    privileged: true
    command: /mesos/build/bin/mesos-master.sh
    ports:
      - "5050:5050"
    links:
      - zookeeper
    environment:
      - MESOS_PORT=5050
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_LOG_DIR=/var/log
      - MESOS_ZK=zk://zookeeper:2181/mesos
