# Docker compose configuration file for building a
# mesos environment

version: '2'

services:
  weavescope:
    image: weaveworks/scope:latest
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
      - "app.weave.addr"
      - "0.0.0.0"

  zookeeper:
    image: jplock/zookeeper:latest
    hostname: zookeeper
    network_mode: "host"
